# Generated by Django 2.2.7 on 2019-11-27 13:59

import bd_sage_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HubInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('api_token', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50, unique=True)),
                ('job_type', models.CharField(choices=[('DUS', 'Delete Unmapped Scans'), ('DEV', 'Delete Empty Versions'), ('Sage', 'Sage Analysis')], max_length=30, validators=[bd_sage_app.models.supported_job_type])),
                ('description', models.TextField(blank=True, max_length=200)),
                ('running', models.BooleanField(default=False)),
                ('trigger_type', models.CharField(choices=[('date', 'date'), ('interval', 'interval'), ('cron', 'cron')], max_length=20, validators=[bd_sage_app.models.supported_trigger_type])),
                ('trigger_value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=1028)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
