# Generated by Django 2.2.7 on 2019-12-02 23:54

import bd_sage_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_sage_app', '0002_auto_20191127_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_args',
            field=models.CharField(default='', help_text='Space separated key-value pairs that provide job-specific arguments', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(help_text='Must be unique', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('DUS', 'Delete Unmapped Scans'), ('DEV', 'Delete Empty Versions'), ('Sage', 'Sage Analysis')], help_text='Must be one of Delete Unmapped Scans, Delete Empty Versions, Sage Analysis', max_length=30, validators=[bd_sage_app.models.supported_job_type]),
        ),
        migrations.AlterField(
            model_name='job',
            name='trigger_args',
            field=models.CharField(help_text="Space separated key-value pairs, e.g. 'second=0 minute=0 hour=0'. See https://apscheduler.readthedocs.io/en/latest/py-modindex.html for details.", max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='trigger_type',
            field=models.CharField(choices=[('date', 'date'), ('interval', 'interval'), ('cron', 'cron')], help_text='Must be one of date, interval, cron', max_length=20, validators=[bd_sage_app.models.supported_trigger_type]),
        ),
    ]
