# Generated by Django 2.2.7 on 2019-12-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_sage_app', '0003_auto_20191202_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_args',
            field=models.CharField(blank=True, help_text='Space separated key-value pairs that provide job-specific arguments', max_length=200),
        ),
    ]
