# Generated by Django 2.2.7 on 2019-12-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_sage_app', '0005_hubinstance_insecure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='running',
            field=models.BooleanField(default=True),
        ),
    ]
