# Generated by Django 2.2.7 on 2019-12-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_sage_app', '0006_auto_20191203_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sage',
            name='filepath',
            field=models.CharField(max_length=1028, unique=True),
        ),
    ]
