# Generated by Django 2.2.7 on 2019-12-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_sage_app', '0007_auto_20191203_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sage',
            name='filepath',
            field=models.CharField(help_text='The path to the JSON-formatted sage results', max_length=1028, unique=True),
        ),
    ]
