# Generated by Django 2.2.7 on 2019-12-06 15:55

import bd_sage_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_sage_app', '0008_auto_20191203_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('DEP', 'Delete Empty Projects'), ('DEV', 'Delete Empty Versions'), ('DUS', 'Delete Unmapped Scans'), ('PRUNEV', 'Prune versions from projects'), ('Sage', 'Sage Analysis')], help_text='Must be one of Delete Empty Projects, Delete Empty Versions, Delete Unmapped Scans, Prune versions from projects, Sage Analysis', max_length=30, validators=[bd_sage_app.models.supported_job_type]),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='result',
            field=models.TextField(editable=False, max_length=2048),
        ),
    ]
